databases:
  - name: price-register-pg
    databaseName: price_register
    user: price_register
    region: frankfurt
    plan: standard

services:
  - type: web
    name: price-register-web
    env: elixir
    plan: starter
    region: frankfurt
    buildCommand: './build.sh'
    startCommand: 'PHX_SERVER=true _build/prod/rel/price_register/bin/price_register start'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: price-register-pg
          property: connectionString
      - fromGroup: price-register-env

envVarGroups:
  - name: price-register-env
    envVars:
      - key: SECRET_KEY_BASE
        sync: false
      - key: ELIXIR_VERSION
        value: 1.15
      - key: ERLANG_VERSION
        value: 26.0