databases:
  - name: price-register-pg
    databaseName: price-register
    user: price-register
    region: frankfurt

services:
  - type: web
    name: price-register-web
    env: ruby
    region: frankfurt
    buildCommand: './build.sh'
    startCommand: '_build/prod/rel/price_register/bin/price_register start'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: price-register-pg
          property: connectionString
      - fromGroup: price-register-env

envVarGroups:
  - name: price-register-env
    envVars:
      - key: SECRET_KEY_BASE
        sync: false
      - key: ELIXIR_VERSION
        value: 1.14.3
      - key: ERLANG_VERSION
        value: 25.2
